config/routes.rb
JsforceSampleApp::Application.routes.draw do
  root "pages#index"
  match '/connect', to: 'pages#connect', via: 'get'
  match '/home', to: 'pages#home', via: 'get'
  match '/query', to: 'pages#query', via: 'get'
  match '/search', to: 'pages#search', via: 'get'
  match '/crud', to: 'pages#crud', via: 'get'
  match '/describe', to: 'pages#describe', via: 'get'
  match '/analytics', to: 'pages#analytics', via: 'get'
  match '/apex_rest', to: 'pages#apex_rest', via: 'get'
  match '/logout', to: 'pages#logout', via: 'get'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def connect
  end

  def home
  end

  def query
  end

  def search
  end

  def crud
  end

  def analytics
  end

  def apex_rest
  end

  def logout
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Get title
  def get_title(page_title)
    base_title = "JSforce Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= get_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <style>pre code { background: transparent; }</style>
    <!-- library -->
    <%= yield :library %>
  </head>
  <body>
    <!-- header -->
    <%= render 'header' %>
    <!-- containt -->
    <div style="min-height: 520px;">
      <%= yield %>
    </div>
    <!-- footer -->
    <%= render 'footer' %>
    <!-- add javascript -->
    <%= yield :scripts %>
    <!-- JSforce -->
    <script type="text/javascript">
      $(document).ready(function(){
        jsforce.browser.init({
          clientId: '3MVG9ZL0ppGP5UrBNnfv8GHjLw9ac.CX_Zko26PdUO6DZ_2Nd5YNn8Xg57RSDAXyYr3XBylQAesapT_1JtWdR',
          redirectUri: 'http://localhost:3000/connect'
        });
      });
    </script>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer class="fn-footer" role="contentinfo" style="padding-bottom: 200px;">
  <div class="container">
    <p>@ Force.com Developer</p>
  </div>
</footer>

app/views/pages/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-branded" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "JSforce Sample App", root_path, { :class => 'navbar-brand navbar-foundation-logo' } %>
    </div>
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#" onclick="javascript:jsforce.browser.login();">Connect Salesforce</a>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/pages/_menu_header.html.erb
<div class="header-menu">
  <span class="menu sb-toggle-left">
    <a class="s1utility s1utility-rows"></a>
  </span>
</div>

app/views/pages/_page_header.html.erb
<div class="page-header page-header-showcase" id="content">
  <div class="container">
    <h1><%= title %></h1>
  </div>
</div>

app/views/pages/_sidebar.html.erb
<div class="sidebar sb-slidebar sb-left" style="padding-top: 60px;">
  <nav>
    <ul class="sb-menu">        
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "Query", query_path %></li>
      <li><%= link_to "Search", search_path %></li>
      <li><%= link_to "CRUD", crud_path %></li>
      <li><%= link_to "Describe", describe_path %></li>
      <li><%= link_to "Analytics", analytics_path %></li>
      <li><%= link_to "Apex REST", apex_rest_path %></li>
      <li><%= link_to "Logout", logout_path %></li>
    </ul>
  </nav>
</div>

app/views/pages/analytics.html.erb
<% provide(:title, 'Analytics') %>

<div class="query-page">
  <!-- main -->
  <div id="sb-site" class="main-color">
    <%= render 'menu_header' %>

    <div class="container">
      <div style="margin-bottom: 20px;">
        <h1 class="header-line">Analytics</h1>
        <button type="button" class="btn btn-primary" data-bind="click: clickSearchBtn">Search</button>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
          </tr>
        </thead>
        <tbody data-bind="foreach: listItems">
          <tr>
            <td>
              <div data-bind="text: result_id"></div>
            </td>
            <td>
              <div data-bind="text: result_name"></div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <!-- sidebar -->
  <%= render 'sidebar' %>
</div>

<% content_for :scripts do %>
<script type="text/javascript">

  var conn = null;

  $(document).ready(function(){
    // Slidebar
    $.slidebars();

    jsforce.browser.on('connect', function(c) {
      conn = c;
    });
  });

  // View Model
  function viewModel() {
    var self = this;
    self.listItems = ko.observableArray([]);
  
    // SearchBtn
    self.clickSearchBtn = function() {
      self.listItems.removeAll();
      // get recent reports
      conn.analytics.reports(function(err, reports) {
        if (err) {
          swal('ERROR!', err, 'error');
          return false;
        }

        for (var i = 0; i < reports.length; i++) {
          self.listItems.push({
             result_id: reports[i].id
            ,result_name: reports[i].name
          });  
        }

        ko.applyBindings(viewModel);
      });
    };
  };

  // Model
  ko.applyBindings(new viewModel());
</script>
<% end %>

app/views/pages/apex_rest.html.erb
<% provide(:title, 'Apex REST') %>

<div class="query-page">
  <!-- main -->
  <div id="sb-site" class="main-color">
    <%= render 'menu_header' %>

    <div class="container">
      <div style="margin-bottom: 20px;">
        <h1 class="header-line">Apex REST (Debug...)</h1>
        <button type="button" class="btn btn-primary" data-bind="click: clickSearchBtn">Search</button>
        <button type="button" class="btn btn-primary" data-bind="click: clickCreateBtn">Create</button>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
          </tr>
        </thead>
        <tbody data-bind="foreach: listItems">
          <tr>
            <td>
              <div data-bind="text: result_id"></div>
            </td>
            <td>
              <div data-bind="text: result_name"></div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <!-- sidebar -->
  <%= render 'sidebar' %>
</div>

<% content_for :scripts do %>
<script type="text/javascript">

  var conn = null;

  $(document).ready(function(){
    // Slidebar
    $.slidebars();

    jsforce.browser.on('connect', function(c) {
      conn = c;
    });
  });

  // View Model
  function viewModel() {
    var self = this;
    self.listItems = ko.observableArray([]);
  
    // SearchBtn
    self.clickSearchBtn = function() {
      self.listItems.removeAll();

      var body = { title: 'Get Account', num : 1 };
      conn.apex.get("/Account/", body, function(err, res) {
        if (err) {
          swal('ERROR!', err, 'error');
          return false;
        }

        for (var i = 0; i < res.length; i++) {
          self.listItems.push({
             result_id: res[i].id
            ,result_name: res[i].name
          });  
        }

        ko.applyBindings(viewModel);
      });
    };

    // CreateBtn
    self.clickCreateBtn = function() {
      // body payload structure is depending to the Apex REST method interface.
      var body = { title: 'Create Account', num : 1 };
      conn.apex.post("/Account/", body, function(err, res) {
        if (err) {
          swal('ERROR!', err, 'error');
          return false;
        }
      });
    };
  };

  // Model
  ko.applyBindings(new viewModel());
</script>
<% end %>

app/views/pages/connect.html.erb
<div class="container">
  <div class="row">
    <h1>Salesforce に接続しました。</h1>
  </div>
</div>

app/views/pages/crud.html.erb
<% provide(:title, 'CRUD') %>

<div class="query-page">
  <!-- main -->
  <div id="sb-site" class="main-color">
    <%= render 'menu_header' %>

    <div class="container">
      <div style="margin-bottom: 20px;">
        <fieldset>
          <h1 class="header-line">CRUD</h1>
          <div class="form-group">
            <label>Account Name</label>
            <input type="text" class="form-control" data-bind="value:input_account_name"></input>
          </div>
        </fieldset>        
        <button type="button" class="btn btn-primary" data-bind="click: clickCreateBtn">Create</button>
        <button type="button" class="btn btn-primary" data-bind="click: clickSearchBtn">Search</button>
      </div>

      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Account Number</th>
          </tr>
        </thead>
        <tbody data-bind="foreach: listItems">
          <tr>
            <td>
              <button type="button" class="btn btn-primary" data-bind="click: $parent.clickDeleteBtn, clickBubble: false">Delete</button>
            </td>
            <td>
              <div data-bind="text: account_name"></div>
            </td>
            <td>
              <div data-bind="text: account_number"></div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <!-- sidebar -->
  <%= render 'sidebar' %>
</div>

<% content_for :scripts do %>
<script type="text/javascript">

  var conn = null;

  $(document).ready(function(){
    // Slidebar
    $.slidebars();

    jsforce.browser.on('connect', function(c) {
      conn = c;
    });
  });

  // View Model
  function viewModel() {
    var self = this;
    self.input_account_name = '';
    self.listItems = ko.observableArray([]);

    // CreateBtn
    self.clickCreateBtn = function() {

      // Multiple records creation
      conn.sobject('Account').create([
        { Name : self.input_account_name }
      ],
      function(err, rets) {
        if (err) {
          swal('ERROR!', err, 'error');
          return false;
        }
        for (var i=0; i < rets.length; i++) {
          if (rets[i].success) {
            swal('Create!', 'Created record id : ' + rets[i].id, 'success');

            // Single record retrieval
            conn.sobject("Account").retrieve(rets[i].id, function(err, account) {
              if (err) {
                swal('ERROR!', err, 'error');
                return false;
              }

              self.listItems.push({
                 account_id: account.id
                ,account_name: account.Name
                ,account_number: account.AccountNuber
              });
            });
          }
        }
      });
    };
  
    // SearchBtn
    self.clickSearchBtn = function() {
      self.listItems.removeAll();
      var query = 'SELECT Id,Name,AccountNumber FROM Account';
      query += ' ORDER BY Name ASC';
      query += ' LIMIT 200';

      conn.query(query, function(err, res) {
        if (err) {
          swal('ERROR!', err, 'error');
          return false;
        }

        for (var i = 0; i < res.records.length; i++) {
          self.listItems.push({
             account_id: res.records[i].Id
            ,account_name: res.records[i].Name
            ,account_number: res.records[i].AccountNumber
          });
        }

        ko.applyBindings(viewModel);
      });

      // DeleteBtn
      self.clickDeleteBtn = function(record) {
        // Single record deletion
        conn.sobject("Account").destroy(record.account_id, function(err, ret) {
          if (err || !ret.success) {
            swal('ERROR!', err, 'error');
            return false;
          }
          swal('Delete!', 'Deleted Successfully : ' + ret.id, 'success');
          self.listItems.remove(record);
        });
      }
    };
  };

  // Model
  ko.applyBindings(new viewModel());
</script>
<% end %>

app/views/pages/describe.html.erb
<% provide(:title, 'Describe') %>

<div class="query-page">
  <!-- main -->
  <div id="sb-site" class="main-color">
    <%= render 'menu_header' %>

    <div class="container">
      <div style="margin-bottom: 20px;">
        <h1>Describe</h1>
        <button type="button" class="btn btn-primary" data-bind="click: clickSearchBtn">Search</button>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Label</th>
            <th>API Name</th>
            <th>Field Type</th>
          </tr>
        </thead>
        <tbody data-bind="foreach: listItems">
          <tr>
            <td>
              <div data-bind="text: meta_label"></div>
            </td>
            <td>
              <div data-bind="text: meta_name"></div>
            </td>
            <td>
              <div data-bind="text: meta_type"></div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <!-- sidebar -->
  <%= render 'sidebar' %>
</div>

<% content_for :scripts do %>
<script type="text/javascript">

  var conn = null;

  $(document).ready(function(){
    // Slidebar
    $.slidebars();

    jsforce.browser.on('connect', function(c) {
      conn = c;
    });
  });

  // View Model
  function viewModel() {
    var self = this;
    self.listItems = ko.observableArray([]);
  
    // SearchBtn
    self.clickSearchBtn = function() {
      self.listItems.removeAll();
      conn.sobject("Account").describe(function(err, meta) {
        if (err) {
          swal('ERROR!', err, 'error');
          return false;
        }

        for (var i = 0; i < meta.fields.length; i++) {
          self.listItems.push({
             meta_label: meta.fields[i].label
            ,meta_name: meta.fields[i].name
            ,meta_type: meta.fields[i].type
          });  
        }

        ko.applyBindings(viewModel);
      });
    };
  };

  // Model
  ko.applyBindings(new viewModel());
</script>
<% end %>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>

<% content_for :library do %>
  <!-- your library -->
<% end %>

<div class="home-page">
  <!-- main -->
  <div id="sb-site" class="main-color">
    <%= render 'menu_header' %>
    <div class="container">
      <h1>
        Hello! <span data-bind="text: userName"></span>
      </h1>
    </div>
  </div>
  <!-- sidebar -->
  <%= render 'sidebar' %>
</div>

<% content_for :scripts do %>
<script type="text/javascript">

  var conn = null;

  $(document).ready(function(){
    // Slidebar
    $.slidebars();

    // Get User
    jsforce.browser.on('connect', function(c) {

      conn = c;

      var query = 'SELECT Id, Name FROM User WHERE Id = ' + '\'' + conn.userInfo.id + '\'' + ' LIMIT 1';
      conn.query(query, function(err, res) {
        if (err) {
          swal('ERROR!', err, 'error');
          return false;
        }
        
        var viewModel = {
          userName: res.records[0].Name + '!!'
        };

        ko.applyBindings(viewModel);
      });
    });
  });
</script>
<% end %>

app/views/pages/index.html.erb
<div class="welcome-page">
  <div class="jumbotron jumbotron-inverse jumbotron-center" id="content">
    <div class="container">
      <h1>Hello Developers</h1>
      <p>Rails &amp; JSforce Sample Application</p>
      <p>
        <%= link_to "Let's Go!", home_path, { :class => "btn btn-lg btn-primary" } %>
      </p>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <ul>
        <li>勉強用につくったRails &amp; JSforceのサンプルアプリです。</li>
        <li>Connect SalesforceボタンでSalesforceに接続できます。</li>
        <li>
          コードはGitHubに公開中です。
          <a  href="https://github.com/tyoshikawa1106/rails-jsforce-sample" target="_blank">
            https://github.com/tyoshikawa1106/rails-jsforce-sample
          </a>
        </li>
        <li>GitHubのコードを動かすにはSalesforce側で接続アプリケーションの設定が必要です。</li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/logout.html.erb
<% provide(:title, 'Logout') %>

<div class="query-page">
  <!-- main -->
  <div id="sb-site" class="main-color">
    <%= render 'menu_header' %>

    <div class="container">
      <div style="margin-bottom: 20px;">
        <h1 class="header-line">Salesforce Connection Logout</h1>
        <button type="button" class="btn btn-primary" onclick="return logout();">Logout</button>
      </div>
    </div>
  </div>
  <!-- sidebar -->
  <%= render 'sidebar' %>
</div>

<% content_for :scripts do %>
<script type="text/javascript">

  var conn = null;

  $(document).ready(function(){
    // Slidebar
    $.slidebars();

    jsforce.browser.on('connect', function(c) {
      conn = c;
    });
  });

  function logout() {
    if(confirm('Logout ?')) {
      jsforce.browser.logout();
      location.href = "https://tyoshikwa1106-jsforce-sample.herokuapp.com";
    }

    return false;
  }
</script>
<% end %>

app/views/pages/search.html.erb
<% provide(:title, 'Search') %>

<div class="query-page">
  <!-- main -->
  <div id="sb-site" class="main-color">
    <%= render 'menu_header' %>

    <div class="container">
      <div style="margin-bottom: 20px;">
        <h1 class="header-line">SOSL Search</h1>
        <button type="button" class="btn btn-primary" data-bind="click: clickSearchBtn">Search</button>
      </div>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody data-bind="foreach: listItems">
          <tr>
            <td>
              <div data-bind="text: result_id"></div>
            </td>
            <td>
              <div data-bind="text: result_name"></div>
            </td>
            <td>
              <div data-bind="text: result_type"></div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <!-- sidebar -->
  <%= render 'sidebar' %>
</div>

<% content_for :scripts do %>
<script type="text/javascript">

  var conn = null;

  $(document).ready(function(){
    // Slidebar
    $.slidebars();

    jsforce.browser.on('connect', function(c) {
      conn = c;
    });
  });

  // View Model
  function viewModel() {
    var self = this;
    self.searchKey = '';
    self.listItems = ko.observableArray([]);
  
    // SearchBtn
    self.clickSearchBtn = function() {
      self.listItems.removeAll();
      var query = 'FIND {Un*} IN ALL FIELDS RETURNING Account(Id, Name LIMIT 5), Contact(Id, Name LIMIT 5), Opportunity(Id, Name LIMIT 5) LIMIT 100';

      conn.search(query,
        function(err, res) {
          if (err) {
            swal('ERROR!', err, 'error');
            return false;
          }
          for (var i = 0; i < res.length; i++) {
            self.listItems.push({
               result_id: res[i].Id
              ,result_name: res[i].Name
              ,result_type: res[i].attributes.type
            });  
          }

          ko.applyBindings(viewModel);
        }
      );
    };

  };

  // Model
  ko.applyBindings(new viewModel());
</script>
<% end %>